package softhing.model;
// Generated 13/11/2016 09:04:01 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Answer generated by hbm2java
 */
@Entity
@Table(name="answer"
    ,catalog="seeker"
)
public class Answer  implements java.io.Serializable {


     private Long ansId;
     private Form form;
     private User user;
     private String answer;
     private Date createdAt;
     private Date updatedAt;
     private Date deletedAt;

    public Answer() {
    }

	
    public Answer(String answer, Date createdAt, Date updatedAt) {
        this.answer = answer;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
    public Answer(Form form, User user, String answer, Date createdAt, Date updatedAt, Date deletedAt) {
       this.form = form;
       this.user = user;
       this.answer = answer;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.deletedAt = deletedAt;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Ans_Id", unique=true, nullable=false)
    public Long getAnsId() {
        return this.ansId;
    }
    
    public void setAnsId(Long ansId) {
        this.ansId = ansId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Frm_Id")
    public Form getForm() {
        return this.form;
    }
    
    public void setForm(Form form) {
        this.form = form;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Us_Id")
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="answer", nullable=false)
    public String getAnswer() {
        return this.answer;
    }
    
    public void setAnswer(String answer) {
        this.answer = answer;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false, length=19)
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at", nullable=false, length=19)
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="deleted_at", length=19)
    public Date getDeletedAt() {
        return this.deletedAt;
    }
    
    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }




}


