package softhing.model;
// Generated 13/11/2016 09:04:01 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Detail generated by hbm2java
 */
@Entity
@Table(name="detail"
    ,catalog="seeker"
)
public class Detail  implements java.io.Serializable {


     private Long DId;
     private Publish publish;
     private String content;
     private Date createdAt;
     private Date updatedAt;
     private Date deletedAt;

    public Detail() {
    }

	
    public Detail(String content, Date createdAt, Date updatedAt) {
        this.content = content;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
    public Detail(Publish publish, String content, Date createdAt, Date updatedAt, Date deletedAt) {
       this.publish = publish;
       this.content = content;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.deletedAt = deletedAt;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="D_Id", unique=true, nullable=false)
    public Long getDId() {
        return this.DId;
    }
    
    public void setDId(Long DId) {
        this.DId = DId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Pub_Id")
    public Publish getPublish() {
        return this.publish;
    }
    
    public void setPublish(Publish publish) {
        this.publish = publish;
    }

    
    @Column(name="content", nullable=false)
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false, length=19)
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at", nullable=false, length=19)
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="deleted_at", length=19)
    public Date getDeletedAt() {
        return this.deletedAt;
    }
    
    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }




}


