package softhing.model;
// Generated 13/11/2016 09:04:01 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Person generated by hbm2java
 */
@Entity
@Table(name="person"
    ,catalog="seeker"
    , uniqueConstraints = {@UniqueConstraint(columnNames="username"), @UniqueConstraint(columnNames="email")} 
)
public class Person  implements java.io.Serializable {


     private Long psnId;
     private String names;
     private String username;
     private String email;
     private String password;
     private Date createdAt;
     private Date updatedAt;
     private Date deletedAt;
     private Set<User> users = new HashSet<User>(0);
     private Set<Admin> admins = new HashSet<Admin>(0);

    public Person() {
    }

	
    public Person(String names, String username, String email, String password, Date createdAt, Date updatedAt) {
        this.names = names;
        this.username = username;
        this.email = email;
        this.password = password;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
    public Person(String names, String username, String email, String password, Date createdAt, Date updatedAt, Date deletedAt, Set<User> users, Set<Admin> admins) {
       this.names = names;
       this.username = username;
       this.email = email;
       this.password = password;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.deletedAt = deletedAt;
       this.users = users;
       this.admins = admins;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Psn_Id", unique=true, nullable=false)
    public Long getPsnId() {
        return this.psnId;
    }
    
    public void setPsnId(Long psnId) {
        this.psnId = psnId;
    }

    
    @Column(name="names", nullable=false)
    public String getNames() {
        return this.names;
    }
    
    public void setNames(String names) {
        this.names = names;
    }

    
    @Column(name="username", unique=true, nullable=false)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="email", unique=true, nullable=false)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="password", nullable=false)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false, length=19)
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at", nullable=false, length=19)
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="deleted_at", length=19)
    public Date getDeletedAt() {
        return this.deletedAt;
    }
    
    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="person")
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="person")
    public Set<Admin> getAdmins() {
        return this.admins;
    }
    
    public void setAdmins(Set<Admin> admins) {
        this.admins = admins;
    }




}


