package softhing.model;
// Generated 13/11/2016 09:04:01 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Place generated by hbm2java
 */
@Entity
@Table(name="place"
    ,catalog="seeker"
)
public class Place  implements java.io.Serializable {


     private Long plId;
     private Admin admin;
     private String name;
     private Double latitude;
     private Double longitude;
     private Date createdAt;
     private Date updatedAt;
     private Date deletedAt;
     private Set<Publish> publishes = new HashSet<Publish>(0);

    public Place() {
    }

	
    public Place(String name, Date createdAt, Date updatedAt) {
        this.name = name;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
    public Place(Admin admin, String name, Double latitude, Double longitude, Date createdAt, Date updatedAt, Date deletedAt, Set<Publish> publishes) {
       this.admin = admin;
       this.name = name;
       this.latitude = latitude;
       this.longitude = longitude;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.deletedAt = deletedAt;
       this.publishes = publishes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Pl_Id", unique=true, nullable=false)
    public Long getPlId() {
        return this.plId;
    }
    
    public void setPlId(Long plId) {
        this.plId = plId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Adm_Id")
    public Admin getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(Admin admin) {
        this.admin = admin;
    }

    
    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="latitude", precision=22, scale=0)
    public Double getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    
    @Column(name="longitude", precision=22, scale=0)
    public Double getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false, length=19)
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at", nullable=false, length=19)
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="deleted_at", length=19)
    public Date getDeletedAt() {
        return this.deletedAt;
    }
    
    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="place")
    public Set<Publish> getPublishes() {
        return this.publishes;
    }
    
    public void setPublishes(Set<Publish> publishes) {
        this.publishes = publishes;
    }




}


