package softhing.model;
// Generated 13/11/2016 09:04:01 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tag generated by hbm2java
 */
@Entity
@Table(name="tag"
    ,catalog="seeker"
)
public class Tag  implements java.io.Serializable {


     private TagId id;
     private ObjectLossed objectLossed;
     private TagClass tagClass;
     private Date createdAt;
     private Date updatedAt;
     private Date deletedAt;

    public Tag() {
    }

	
    public Tag(TagId id, ObjectLossed objectLossed, TagClass tagClass, Date createdAt, Date updatedAt) {
        this.id = id;
        this.objectLossed = objectLossed;
        this.tagClass = tagClass;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
    public Tag(TagId id, ObjectLossed objectLossed, TagClass tagClass, Date createdAt, Date updatedAt, Date deletedAt) {
       this.id = id;
       this.objectLossed = objectLossed;
       this.tagClass = tagClass;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.deletedAt = deletedAt;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="tcId", column=@Column(name="TC_Id", nullable=false) ), 
        @AttributeOverride(name="olId", column=@Column(name="OL_Id", nullable=false) ) } )
    public TagId getId() {
        return this.id;
    }
    
    public void setId(TagId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="OL_Id", nullable=false, insertable=false, updatable=false)
    public ObjectLossed getObjectLossed() {
        return this.objectLossed;
    }
    
    public void setObjectLossed(ObjectLossed objectLossed) {
        this.objectLossed = objectLossed;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TC_Id", nullable=false, insertable=false, updatable=false)
    public TagClass getTagClass() {
        return this.tagClass;
    }
    
    public void setTagClass(TagClass tagClass) {
        this.tagClass = tagClass;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false, length=19)
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at", nullable=false, length=19)
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="deleted_at", length=19)
    public Date getDeletedAt() {
        return this.deletedAt;
    }
    
    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }




}


