package softhing.model;
// Generated 13/11/2016 09:04:01 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TagClass generated by hbm2java
 */
@Entity
@Table(name="tag_class"
    ,catalog="seeker"
    , uniqueConstraints = @UniqueConstraint(columnNames="name") 
)
public class TagClass  implements java.io.Serializable {


     private Long tcId;
     private String name;
     private String color;
     private String size;
     private Date createdAt;
     private Date updatedAt;
     private Date deletedAt;
     private Set<Tag> tags = new HashSet<Tag>(0);

    public TagClass() {
    }

	
    public TagClass(String name, String color, String size, Date createdAt, Date updatedAt) {
        this.name = name;
        this.color = color;
        this.size = size;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
    public TagClass(String name, String color, String size, Date createdAt, Date updatedAt, Date deletedAt, Set<Tag> tags) {
       this.name = name;
       this.color = color;
       this.size = size;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.deletedAt = deletedAt;
       this.tags = tags;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="TC_Id", unique=true, nullable=false)
    public Long getTcId() {
        return this.tcId;
    }
    
    public void setTcId(Long tcId) {
        this.tcId = tcId;
    }

    
    @Column(name="name", unique=true, nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="color", nullable=false)
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }

    
    @Column(name="size", nullable=false)
    public String getSize() {
        return this.size;
    }
    
    public void setSize(String size) {
        this.size = size;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false, length=19)
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at", nullable=false, length=19)
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="deleted_at", length=19)
    public Date getDeletedAt() {
        return this.deletedAt;
    }
    
    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tagClass")
    public Set<Tag> getTags() {
        return this.tags;
    }
    
    public void setTags(Set<Tag> tags) {
        this.tags = tags;
    }




}


