package softhing.model;
// Generated 13/11/2016 09:04:01 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TagId generated by hbm2java
 */
@Embeddable
public class TagId  implements java.io.Serializable {


     private long tcId;
     private long olId;

    public TagId() {
    }

    public TagId(long tcId, long olId) {
       this.tcId = tcId;
       this.olId = olId;
    }
   


    @Column(name="TC_Id", nullable=false)
    public long getTcId() {
        return this.tcId;
    }
    
    public void setTcId(long tcId) {
        this.tcId = tcId;
    }


    @Column(name="OL_Id", nullable=false)
    public long getOlId() {
        return this.olId;
    }
    
    public void setOlId(long olId) {
        this.olId = olId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TagId) ) return false;
		 TagId castOther = ( TagId ) other; 
         
		 return (this.getTcId()==castOther.getTcId())
 && (this.getOlId()==castOther.getOlId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getTcId();
         result = 37 * result + (int) this.getOlId();
         return result;
   }   


}


